version: '3.8'

services:
  worker:
    build:
      context: ./synchronizer
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      DB_URL: mongodb+srv://shareuser:3lZZIJuv5sqfNNGJ@devshared.iya8g91.mongodb.net
      DB_DATABASE: shareprop
      BLOCKCHAIN_PROVIDER_URL: ganache.daftarproperti.org
      DP_ABI_VERSION: "1"
      COLLECTION_NAME: properties
      ERROR_NOTIF_CHANNEL: ""
      SLACK_WEBHOOK_UR: ""
      DP_CONTRACT_ADDRESS: 0xD5FbDbd20cf80521fAF9c7968a35b79959BF5F51
      REVEAL_BASE_URL: "https://reveal.daftarproperti.org"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      DB_URL: mongodb+srv://shareuser:3lZZIJuv5sqfNNGJ@devshared.iya8g91.mongodb.net
      DB_DATABASE: shareprop
      BLOCKCHAIN_PROVIDER_URL: ganache.daftarproperti.org
      DP_ABI_VERSION: "1"
      COLLECTION_NAME: properties
      ERROR_NOTIF_CHANNEL: ""
      SLACK_WEBHOOK_UR: ""
      DP_CONTRACT_ADDRESS: 0xD5FbDbd20cf80521fAF9c7968a35b79959BF5F51
      REVEAL_BASE_URL: "https://reveal.daftarproperti.org"

  # mongo:
  #   image: mongo:6.0.16
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo-data:/data/db

volumes:
  mongo-data:
