# Ansible playbook.yml
---
- hosts: all
  become: true
  tasks:
    - name: Install Git
      apt:
        name: git
        state: present
        update_cache: true

    - name: Install Docker via official script
      shell: curl -fsSL https://get.docker.com | sh

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.24.7/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Remove existing app directory
      file:
        path: /home/ubuntu/new-moruma
        state: absent

    - name: Clone app repository
      git:
        repo: https://github.com/vwijaya03/property-listing.git
        dest: /home/ubuntu/new-moruma

    - name: Stop and remove all running Docker containers
      shell: docker ps -q | xargs -r docker rm -f

    - name: Run docker-compose and log output
      shell: docker-compose up -d --build && docker-compose ps && docker-compose logs --tail=20
      args:
        chdir: /home/ubuntu/new-moruma