name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:1.8.5-cli
      options: --entrypoint /bin/sh

    env:
      SSH_KEY_FILE: ~/.ssh/id_rsa

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Install Ansible
        run: |
          apk add --no-cache py3-pip bash openssh-client
          pip3 install ansible

      - name: Fix folder ownership before sync
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@47.130.15.129 "sudo chown -R ubuntu:ubuntu /home/ubuntu/new-moruma || true"

      - name: Copy repo to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@47.130.15.129 "mkdir -p /home/ubuntu/new-moruma"
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ ubuntu@47.130.15.129:/home/ubuntu/new-moruma

      - name: Run Terraform apply for provisioning
        run: |
          cd infrastructure
          terraform init
          terraform taint null_resource.deploy_to_existing_vps || true
          terraform apply -auto-approve
