name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04
      options: --entrypoint /bin/bash

    env:
      SSH_KEY_PATH: /root/.ssh/id_rsa

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key file
        run: |
          mkdir -p /root/.ssh
          echo "${{ secrets.VPS_KEY }}" > $SSH_KEY_PATH
          chmod 600 $SSH_KEY_PATH
      
      - name: Create .env files for app and worker
        run: |
          for path in . ./synchronizer; do
            mkdir -p "$path"
            echo "DB_URL=${{ secrets.DB_URL }}" > "$path/.env"
            echo "DB_DATABASE=shareprop" >> "$path/.env"
            echo "BLOCKCHAIN_PROVIDER_URL=ganache.daftarproperti.org" >> "$path/.env"
            echo "DP_ABI_VERSION=1" >> "$path/.env"
            echo "COLLECTION_NAME=properties" >> "$path/.env"
            echo "ERROR_NOTIF_CHANNEL=" >> "$path/.env"
            echo "SLACK_WEBHOOK_UR=" >> "$path/.env"
            echo "DP_CONTRACT_ADDRESS=0xD5FbDbd20cf80521fAF9c7968a35b79959BF5F51" >> "$path/.env"
            echo "REVEAL_BASE_URL=https://reveal.daftarproperti.org" >> "$path/.env"
          done

      - name: Install all prerequisites
        run: |
          apt-get update
          apt-get install -y software-properties-common curl unzip gnupg2 ssh python3-pip rsync openssh-client
          pip3 install --break-system-packages ansible
          curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com noble main" > /etc/apt/sources.list.d/hashicorp.list
          apt-get update && apt-get install -y terraform

      - name: Add SSH key to agent
        run: |
          eval $(ssh-agent -s)
          ssh-add $SSH_KEY_PATH

      - name: Fix folder ownership before sync
        run: |
          ssh -i $SSH_KEY_PATH -o StrictHostKeyChecking=no ubuntu@47.130.15.129 "sudo chown -R ubuntu:ubuntu /home/ubuntu/new-moruma || true"

      - name: Copy repo to VPS
        run: |
          ssh -i $SSH_KEY_PATH -o StrictHostKeyChecking=no ubuntu@47.130.15.129 "mkdir -p /home/ubuntu/new-moruma"
          rsync -avz --delete -e "ssh -i $SSH_KEY_PATH -o StrictHostKeyChecking=no" ./ ubuntu@47.130.15.129:/home/ubuntu/new-moruma

      - name: Run Terraform apply for provisioning
        run: |
          cd infrastructure
          terraform init
          terraform taint null_resource.deploy_to_existing_vps || true
          terraform apply -auto-approve
