name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04
      options: --entrypoint /bin/bash

    env:
      SSH_KEY_FILE: ~/.ssh/id_rsa

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key file
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Install Terraform & Ansible
        run: |
          apt-get update
          apt-get install -y software-properties-common curl unzip gnupg2 ssh python3-pip
          pip3 install --break-system-packages ansible
          curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com noble main" > /etc/apt/sources.list.d/hashicorp.list
          apt-get update && apt-get install -y terraform

      - name: Fix folder ownership before sync
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@47.130.15.129 "sudo chown -R ubuntu:ubuntu /home/ubuntu/new-moruma || true"

      - name: Copy repo to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@47.130.15.129 "mkdir -p /home/ubuntu/new-moruma"
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ ubuntu@47.130.15.129:/home/ubuntu/new-moruma

      - name: Run Terraform apply for provisioning
        run: |
          cd infrastructure
          terraform init
          terraform taint null_resource.deploy_to_existing_vps || true
          terraform apply -auto-approve
