name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_KEY }}

      - name: Copy repo to VPS
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@47.130.15.129 "mkdir -p /home/ubuntu/new-moruma"
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./ ubuntu@47.130.15.129:/home/ubuntu/new-moruma

      - name: Deploy on VPS
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@47.130.15.129 << 'EOF'
            cd /home/ubuntu/new-moruma
            docker-compose down
            docker-compose up -d --build
          EOF